export const RATE_OF_ANIMATION_SLOWDOWN: number = 1.2;
export const DEFAULT_FADE_IN_OUT_DURATION_MS: number = 100;
export const FALLBACK_COUNTDOWN_DURATION_MS: number = 20000;
export const DEFAULT_DELAY_BETWEEN_FADE_IN_AND_MAIN_ANIMATION_MS: number = 100;
export const MAXIMUM_LEVEL_POINTS = 1000;
export const TOTAL_NUM_STARS = 5;