load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "settings",
    srcs = [
        "settings.py",
    ],
    visibility = ["//cheetahweb:__pkg__"],
)

py_library(
    name = "urls",
    srcs = [
        "urls.py",
    ],
    visibility = ["//cheetahweb:__pkg__"],
)

py_library(
    name = "wsgi",
    srcs = [
        "wsgi.py",
    ],
    visibility = ["//cheetahweb:__pkg__"],
)

py_library(
    name = "asgi",
    srcs = [
        "asgi.py",
    ],
    visibility = ["//cheetahweb:__pkg__"],
)
